In [1]:
from RandomForest import RandomForest
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import datasets
from sklearn.ensemble import RandomForestClassifier
from utils.utils import obtain_bootstrap_idxs, obtain_bootstrap_samples

In [2]:
x = np.array([10,11,12,13,14,15,16,17,18,19,20])
y = np.array([90,91,92,93,94,95,96,97,98,99,100])

In [3]:
idxs, oob_idxs = obtain_bootstrap_idxs(x)
print(idxs)
print(oob_idxs)

len(set(idxs).union(set(oob_idxs))) == x.size

[ 2 10  8  8  1  5  2  8  2  3  5]
[0 4 6 7 9]


True

In [4]:
obtain_bootstrap_samples(x, y)

(array([13, 17, 20, 19, 17, 18, 15, 17, 14, 15, 14]),
 array([10, 11, 12, 16]),
 array([ 93,  97, 100,  99,  97,  98,  95,  97,  94,  95,  94]),
 array([90, 91, 92, 96]))

In [5]:
data = datasets.load_breast_cancer()
X, y = data.data, data.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=1234
)

In [10]:
rf = RandomForest(min_samples_split=2, max_depth=100, compute_oob = True)
rf.fit(X_train, y_train)
predictions = rf.predict(X_test)
acc = accuracy_score(y_test, predictions)
print(acc)

0.9210526315789473


In [11]:
rf.oob_score

0.9322130143341576

In [22]:
rng = np.random.default_rng(1)
rng2 = np.random.default_rng(1)

In [25]:
rng.random()

0.9504636963259353

In [19]:
new_rng = np.random.default_rng(rng2)

In [21]:
new_rng.random()

0.9486494471372439

In [24]:
rng2.random()

0.5118216247002567